[package]
name = "genegene"
version = "0.1.0"
authors = ["Kerollmops <clement@meilisearch.com>"]
edition = "2018"

[dependencies]
bstr = "0.2.14"
rand = "0.8.0"
rand_distr = "0.4.0"
rayon = "1.5.0"
# reustmann = "0.2.0"
reustmann = { path = "../reustmann" }
